uav:
  J:
    J1: 1.395e-5
    J2: 1.436e-5
    J3: 2.173e-5
  m: 0.035
  d: 0.05
  ctf: 0.025134

controller:
  kx: 4  #2.265
  kv: 1.5     #0.6
  kr: 0.5    #0.01
  kOmega: 0.1   #0.001















###################################
takingoff:
  kx: 1.5  #2.265
  kv: 0.4  #0.4
  kr: 6 #0.00065 #0.00062
  kOmega: 0.0035 #0.000009 #0.0004
###################################


trajectory:
  x0:
    x01: 0
    x02: 0
    x03: 0
  v0:
    v01: 0
    v02: 0
    v03: 0
  R0:
    R0_r1:
      r1_1: 1
      r1_2: 0
      r1_3: 0
    R0_r2:
      r2_1: 0
      r2_2: 1
      r2_3: 0
    R0_r3:
      r3_1: 0
      r3_2: 0
      r3_3: 1
  Omega0:
      Omega01: 0
      Omega02: 0
      Omega03: 0